#line 2 "lexico.c"

#line 4 "lexico.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[251] =
    {   0,
        0,    0,   80,   79,    1,    2,   26,   79,   19,   30,
       79,   10,   11,   17,   15,   12,   16,   13,   18,   75,
       73,   14,    5,   71,   20,   71,   21,   78,   78,    8,
        9,   29,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,    6,
       28,    7,   27,    1,   70,    0,   66,   69,   23,   67,
        0,   24,    0,   73,   25,    0,    0,    0,   75,    0,
       74,   73,   73,   73,   72,   71,   72,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   35,
       78,   78,   78,   78,   78,   78,   31,   78,   78,   78,

       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       22,   65,    0,    0,    0,    3,   76,   75,   76,   74,
       74,   73,   73,   68,   72,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       36,   78,   78,   53,   78,   78,   34,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,    0,    4,
       77,    0,   76,   77,    0,   76,   74,   74,   74,   78,
       52,   78,   78,   56,   41,   60,   78,   78,   78,   78,
       32,   78,   78,   78,   39,   78,   55,   51,   64,   78,
       78,   78,   78,   78,   78,   62,   49,   78,   78,    0,

        4,    0,   76,   76,   74,   78,   78,   37,   47,   78,
       78,   78,   63,   46,   58,   78,   78,   78,   54,   78,
       78,   78,   78,   33,   61,   78,   78,   78,   59,   78,
       50,   40,   48,   42,   78,   78,   57,   78,   43,   78,
       78,   78,   38,   78,   78,   45,   78,   44,   71,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   32,   30,   30,   30,   30,   33,   30,   30,
       34,    1,   35,   36,   30,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   33,
       58,   30,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[259] =
    {   0,
        0,    0,  203, 1051,  200, 1051,  177,  193,  174,   56,
        0, 1051, 1051,  169,   52, 1051,   59, 1051,   69,   48,
       69, 1051, 1051,   61,  168,   66, 1051,   76,   79, 1051,
     1051,  166,   84,   87,   91,  101,   96,   80,  103,  137,
      140,  143,  146,  149,  152,  155,  158,  164,  104, 1051,
       51, 1051, 1051,  186, 1051,  180, 1051, 1051, 1051, 1051,
      176, 1051,  177,  188, 1051,  167,  149,  198,  203,  206,
      210,  213,  223,  228,  126, 1051,  108,    0,  231,  234,
      238,  244,  247,  250,  254,  258,  261,  265,  273,  282,
      291,  294,  299,  302,  305,  308,  311,  314,  317,  328,

      321,  332,  336,  341,  346,  352,  358,  363,  366,  369,
     1051, 1051,  135,   96,  141, 1051,  380,  398,  414,  440,
      418,  466,  497, 1051,  103,  374,  411,  387,  433,  455,
      458,  469,  483,  444,  472,  493,  486,  500,  515,  523,
      528,  531,  537,  540,  544,  547,  550,  553,  556,  559,
      565,  571,  575,  587,  580,  590,  594,  601,  118, 1051,
     1051,  620, 1051,  605,  628,  609,  632,  650,  654,  635,
      638,  668,  671,  674,  677,  680,  683,  686,  689,  693,
      696,  701,  704,  707,  710,  715,  720,  728,  731,  736,
      739,  745,  748,  751,  754,  757,  760,  765,  768,   88,

       80,  777,  783,  786,  803,  799,  816,  819,  822,  829,
      832,  839,  842,  845,  848,  851,  854,  857,  864,  868,
      871,  877,  880,  884,  891,  894,  899,  902,  909,  912,
      915,  918,  921,  927,  930,  940,  943,  947,  950,  955,
      958,  961,  964,  967,  972,  975,  980,  986,  991, 1051,
     1026, 1030, 1034,   68, 1038, 1042,   64, 1046
    } ;

static yyconst flex_int16_t yy_def[259] =
    {   0,
      250,    1,  250,  250,  250,  250,  250,  251,  250,  250,
      252,  250,  250,  250,  250,  250,  250,  250,  250,  253,
      253,  250,  250,  250,  250,  250,  250,  254,  254,  250,
      250,  250,  254,  254,  254,  254,  254,   35,   35,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  250,
      250,  250,  250,  250,  250,  251,  250,  250,  250,  250,
      250,  250,  253,  253,  250,  255,  256,  250,  253,  253,
      250,  253,  253,  250,  250,  250,  250,  257,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      250,  250,  255,  255,  256,  250,  250,  253,  253,  250,
      250,  253,  253,  250,  250,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  258,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  255,

      255,  250,  250,  250,  250,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,    0,
      250,  250,  250,  250,  250,  250,  250,  250
    } ;

static yyconst flex_int16_t yy_nxt[1114] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   28,
       28,   29,   28,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   28,   40,   28,   41,   42,   43,   28,
       44,   45,   46,   47,   28,   48,   49,   28,   50,   51,
       52,   53,   59,   62,   69,   69,   70,   78,   63,   64,
       64,   79,   65,   60,   58,   63,   64,   64,   60,   66,
       71,   58,   75,   76,   67,   72,   73,   73,   76,   77,
      114,   58,   78,   78,   78,   78,   78,   78,  114,   74,

       78,   78,   78,   78,   78,   78,  159,   78,   78,   78,
      111,  160,   78,   78,   78,   74,   92,   78,   78,   78,
       78,   78,   78,   79,   93,  124,   94,   85,  159,   95,
      124,  125,   80,  201,   86,   81,   82,   87,   83,   79,
       88,   89,   91,  116,   84,  114,   79,  110,  124,   79,
       90,  116,   96,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,  114,   97,  100,
       78,   78,   78,  112,   57,   98,  101,   54,   60,   99,
       55,   58,  104,   70,   70,   70,   58,   57,  105,   55,

      102,   54,  250,  103,   72,   73,   73,  250,  106,  108,
      250,  107,  250,  109,  117,  117,  117,  250,   74,  118,
      118,  119,  119,  119,  119,  250,  120,  120,  120,  122,
      122,  122,  250,  250,   74,  121,  121,  121,  121,  122,
      123,  123,  250,   74,  117,  117,  117,   78,   78,   78,
       78,   78,   78,   74,   78,   78,   78,  250,  250,   74,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   74,
       78,   78,   78,  250,   78,   78,   78,   78,   78,   78,
      127,   78,   78,   78,  250,  126,  250,  129,  250,   78,
       78,   78,  250,  128,  132,  250,  250,  133,   78,   78,

       78,  250,  250,  130,  250,  250,  131,   78,   78,   78,
       78,   78,   78,  134,  135,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,  136,   78,   78,   78,
      138,  250,  250,  137,   78,   78,   78,  139,   78,   78,
       78,  140,   78,   78,   78,  250,  141,   78,   78,   78,
      250,  142,   78,   78,   78,  145,  143,  144,   78,   78,
       78,  250,  146,  149,   78,   78,   78,  147,  148,   78,
       78,   78,   78,   78,   78,   78,   78,   78,  152,  250,
       78,   78,   78,  250,  150,  151,  117,  117,  117,  154,

      250,  250,  153,   78,   78,   78,  161,  162,  163,  250,
      156,  250,  157,  158,  118,  118,  119,  155,  170,  161,
      162,  163,  250,  250,  164,  165,  166,   78,   78,   78,
      119,  119,  119,  172,  121,  121,  121,  164,  165,  166,
      164,  165,  166,  121,  121,  121,  121,  250,  250,   78,
       78,   78,  250,  164,  165,  166,  120,  120,  120,  250,
       78,   78,   78,  171,  250,  121,  167,  168,  169,  173,
      250,   78,   78,   78,   78,   78,   78,  250,  250,  161,
      162,  163,  122,  122,  122,   78,   78,   78,   78,   78,
       78,  250,  164,  165,  166,  174,   74,  178,  175,   78,

       78,   78,   78,   78,   78,  164,  165,  166,  179,   78,
       78,   78,   74,  122,  123,  123,   78,   78,   78,  250,
      176,  250,  250,  164,  165,  166,  181,   74,  250,  250,
      180,   78,   78,   78,  250,  177,  164,  165,  166,   78,
       78,   78,  250,   74,   78,   78,   78,   78,   78,   78,
      250,  183,  182,   78,   78,   78,   78,   78,   78,  184,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,  250,  250,
      185,   78,   78,   78,  250,  250,  187,   78,   78,   78,
      186,   78,   78,   78,  250,  188,   78,   78,   78,  189,

      250,  250,  190,   78,   78,   78,   78,   78,   78,  250,
       78,   78,   78,  191,  250,  250,  192,   78,   78,   78,
      196,  117,  117,  117,  193,  117,  117,  117,  194,  197,
      198,  202,  250,  202,  250,  195,  203,  203,  203,  202,
      250,  202,  250,  250,  204,  204,  204,  199,  121,  121,
      121,   78,   78,   78,   78,   78,   78,  121,  121,  121,
      121,  202,  250,  202,  250,  250,  205,  205,  205,  250,
      121,  121,  121,  250,  250,  121,  121,  121,  121,  121,
      121,  121,  121,  206,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,

       78,   78,   78,   78,   78,   78,   78,   78,  207,   78,
       78,   78,   78,   78,   78,  250,  208,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,  250,
      210,   78,   78,   78,  250,  209,   78,   78,   78,  212,
      250,  213,  250,  211,   78,   78,   78,   78,   78,   78,
      214,  216,   78,   78,   78,   78,   78,   78,  250,  250,
      215,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,  250,
      217,   78,   78,   78,   78,   78,   78,  250,  250,  221,
      218,  250,  220,  203,  203,  203,  250,  250,  219,  203,

      203,  203,  204,  204,  204,  250,  222,  250,  224,  161,
      250,  163,  161,  162,  163,   78,   78,   78,  223,  205,
      205,  205,  161,  250,  163,  161,  162,  163,  121,  167,
      121,  169,   78,   78,   78,   78,   78,   78,   78,   78,
       78,  225,  161,  250,  163,   78,   78,   78,   78,   78,
       78,  250,  226,  250,  250,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,  250,  227,  228,  229,
       78,   78,   78,  250,   78,   78,   78,   78,   78,   78,
      250,  250,  231,   78,   78,   78,   78,   78,   78,  230,

       78,   78,   78,  250,  250,  232,  233,   78,   78,   78,
       78,   78,   78,  250,  234,   78,   78,   78,   78,   78,
       78,  235,  250,  250,  236,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
      250,  250,  237,   78,   78,   78,   78,   78,   78,  250,
      240,  250,  250,  238,  250,  239,   78,   78,   78,   78,
       78,   78,  250,   78,   78,   78,   78,   78,   78,  250,
      241,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,  242,  243,   78,   78,
       78,   78,   78,   78,  250,  244,   78,   78,   78,  250,

      250,  246,   78,   78,   78,  250,  245,   78,   78,   78,
      250,  250,  250,  250,  250,  250,  247,  250,  250,  250,
      250,  249,  250,  250,  250,  248,   56,   56,   56,   56,
       61,   61,  250,   61,   68,  250,   68,   68,  113,  113,
      113,  113,  115,  115,  115,  115,  200,  200,  200,  200,
        3,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250
    } ;

static yyconst flex_int16_t yy_chk[1114] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   10,   15,   20,   20,   20,  257,   15,   15,
       15,  254,   17,   51,   15,   17,   17,   17,   10,   19,
       20,   17,   24,   24,   19,   21,   21,   21,   26,   26,
      201,   19,   28,   28,   28,   29,   29,   29,  200,   21,

       33,   33,   33,   34,   34,   34,  114,   35,   35,   35,
       51,  114,   37,   37,   37,   21,   38,   36,   36,   36,
       49,   49,   49,   38,   38,  125,   38,   35,  159,   38,
       77,   77,   29,  159,   35,   33,   34,   35,   34,   39,
       35,   36,   37,  115,   34,  113,   39,   49,   75,   39,
       36,   67,   39,   40,   40,   40,   41,   41,   41,   42,
       42,   42,   43,   43,   43,   44,   44,   44,   45,   45,
       45,   46,   46,   46,   47,   47,   47,   66,   40,   42,
       48,   48,   48,   61,   56,   40,   43,   54,   32,   41,
       25,   14,   45,   63,   63,   63,    9,    8,   46,    7,

       43,    5,    3,   44,   64,   64,   64,    0,   46,   47,
        0,   46,    0,   48,   68,   68,   68,    0,   64,   69,
       69,   69,   70,   70,   70,    0,   71,   71,   71,   72,
       72,   72,    0,    0,   64,   71,   71,   71,   71,   73,
       73,   73,    0,   72,   74,   74,   74,   79,   79,   79,
       80,   80,   80,   73,   81,   81,   81,    0,    0,   72,
       82,   82,   82,   83,   83,   83,   84,   84,   84,   73,
       85,   85,   85,    0,   86,   86,   86,   87,   87,   87,
       81,   88,   88,   88,    0,   80,    0,   83,    0,   89,
       89,   89,    0,   82,   86,    0,    0,   87,   90,   90,

       90,    0,    0,   84,    0,    0,   85,   91,   91,   91,
       92,   92,   92,   88,   89,   93,   93,   93,   94,   94,
       94,   95,   95,   95,   96,   96,   96,   97,   97,   97,
       98,   98,   98,   99,   99,   99,   90,  101,  101,  101,
       92,    0,    0,   91,  100,  100,  100,   93,  102,  102,
      102,   94,  103,  103,  103,    0,   95,  104,  104,  104,
        0,   96,  105,  105,  105,   99,   98,   98,  106,  106,
      106,    0,  100,  103,  107,  107,  107,  101,  102,  108,
      108,  108,  109,  109,  109,  110,  110,  110,  106,    0,
      126,  126,  126,    0,  104,  105,  117,  117,  117,  108,

        0,    0,  107,  128,  128,  128,  117,  117,  117,    0,
      109,    0,  109,  110,  118,  118,  118,  108,  126,  117,
      117,  117,    0,    0,  118,  118,  118,  127,  127,  127,
      119,  119,  119,  128,  121,  121,  121,  118,  118,  118,
      119,  119,  119,  121,  121,  121,  121,    0,    0,  129,
      129,  129,    0,  119,  119,  119,  120,  120,  120,    0,
      134,  134,  134,  127,    0,  120,  120,  120,  120,  129,
        0,  130,  130,  130,  131,  131,  131,    0,    0,  120,
      120,  120,  122,  122,  122,  132,  132,  132,  135,  135,
      135,    0,  122,  122,  122,  130,  122,  134,  131,  133,

      133,  133,  137,  137,  137,  122,  122,  122,  135,  136,
      136,  136,  122,  123,  123,  123,  138,  138,  138,    0,
      132,    0,    0,  123,  123,  123,  137,  123,    0,    0,
      136,  139,  139,  139,    0,  133,  123,  123,  123,  140,
      140,  140,    0,  123,  141,  141,  141,  142,  142,  142,
        0,  139,  138,  143,  143,  143,  144,  144,  144,  140,
      145,  145,  145,  146,  146,  146,  147,  147,  147,  148,
      148,  148,  149,  149,  149,  150,  150,  150,    0,    0,
      142,  151,  151,  151,    0,    0,  145,  152,  152,  152,
      143,  153,  153,  153,    0,  146,  155,  155,  155,  148,

        0,    0,  149,  154,  154,  154,  156,  156,  156,    0,
      157,  157,  157,  150,    0,    0,  151,  158,  158,  158,
      155,  164,  164,  164,  152,  166,  166,  166,  153,  156,
      157,  162,    0,  162,    0,  154,  162,  162,  162,  165,
        0,  165,    0,    0,  165,  165,  165,  158,  167,  167,
      167,  170,  170,  170,  171,  171,  171,  167,  167,  167,
      167,  168,    0,  168,    0,    0,  168,  168,  168,    0,
      169,  169,  169,    0,    0,  168,  168,  168,  168,  169,
      169,  169,  169,  170,  172,  172,  172,  173,  173,  173,
      174,  174,  174,  175,  175,  175,  176,  176,  176,  177,

      177,  177,  178,  178,  178,  179,  179,  179,  172,  180,
      180,  180,  181,  181,  181,    0,  173,  182,  182,  182,
      183,  183,  183,  184,  184,  184,  185,  185,  185,    0,
      178,  186,  186,  186,    0,  177,  187,  187,  187,  180,
        0,  182,    0,  179,  188,  188,  188,  189,  189,  189,
      183,  186,  190,  190,  190,  191,  191,  191,    0,    0,
      184,  192,  192,  192,  193,  193,  193,  194,  194,  194,
      195,  195,  195,  196,  196,  196,  197,  197,  197,    0,
      190,  198,  198,  198,  199,  199,  199,    0,    0,  194,
      191,    0,  193,  202,  202,  202,    0,    0,  192,  203,

      203,  203,  204,  204,  204,    0,  195,    0,  199,  203,
        0,  203,  204,  204,  204,  206,  206,  206,  198,  205,
      205,  205,  203,    0,  203,  204,  204,  204,  205,  205,
      205,  205,  207,  207,  207,  208,  208,  208,  209,  209,
      209,  206,  205,    0,  205,  210,  210,  210,  211,  211,
      211,    0,  207,    0,    0,  212,  212,  212,  213,  213,
      213,  214,  214,  214,  215,  215,  215,  216,  216,  216,
      217,  217,  217,  218,  218,  218,    0,  210,  211,  212,
      219,  219,  219,    0,  220,  220,  220,  221,  221,  221,
        0,    0,  217,  222,  222,  222,  223,  223,  223,  216,

      224,  224,  224,    0,    0,  218,  220,  225,  225,  225,
      226,  226,  226,    0,  221,  227,  227,  227,  228,  228,
      228,  222,    0,    0,  223,  229,  229,  229,  230,  230,
      230,  231,  231,  231,  232,  232,  232,  233,  233,  233,
        0,    0,  226,  234,  234,  234,  235,  235,  235,    0,
      230,    0,    0,  227,    0,  228,  236,  236,  236,  237,
      237,  237,    0,  238,  238,  238,  239,  239,  239,    0,
      235,  240,  240,  240,  241,  241,  241,  242,  242,  242,
      243,  243,  243,  244,  244,  244,  236,  238,  245,  245,
      245,  246,  246,  246,    0,  240,  247,  247,  247,    0,

        0,  242,  248,  248,  248,    0,  241,  249,  249,  249,
        0,    0,    0,    0,    0,    0,  244,    0,    0,    0,
        0,  247,    0,    0,    0,  245,  251,  251,  251,  251,
      252,  252,    0,  252,  253,    0,  253,  253,  255,  255,
      255,  255,  256,  256,  256,  256,  258,  258,  258,  258,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.yy"
/*
** Projeto Compiladores - 2011.2 **
** UFCG - DSC	 		 **	
** Prof.: Franklin Ramalho	 **
** Equipe:			 **
**	Adalberto Teixeira	 **
**	Andrey Menezes 		 **
** 	Augusto Macedo		 **
** Ling. Fonte: Java		 **
*/
#line 13 "lexico.yy"
#include "tokens.h"
#include <string.h>
extern int column; // importa variavel do sintatico
extern int line; // importa variavel do sintatico
extern char* yytext;
void moveCol();
void moveLine();
#line 798 "lexico.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 53 "lexico.yy"


#line 983 "lexico.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 251 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1051 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "lexico.yy"
{moveCol();}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 56 "lexico.yy"
{moveLine();}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 57 "lexico.yy"
{moveLine();}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 58 "lexico.yy"
{moveCol();}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 59 "lexico.yy"
{moveCol();return PT_VIRGULA;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 "lexico.yy"
{moveCol();return BEG;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "lexico.yy"
{moveCol();return END;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 62 "lexico.yy"
{moveCol();return OPEN_COLC;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 63 "lexico.yy"
{moveCol();return CLOSE_COLC;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 64 "lexico.yy"
{moveCol();return OPEN_PAREN;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "lexico.yy"
{moveCol();return CLOSE_PAREN;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 "lexico.yy"
{moveCol();return VIRGULA;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "lexico.yy"
{moveCol();return POINT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "lexico.yy"
{moveCol();return TWO_POINTS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "lexico.yy"
{moveCol();return PLUS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 "lexico.yy"
{moveCol();return MINUS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 "lexico.yy"
{moveCol();return MULT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "lexico.yy"
{moveCol();return DIV;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "lexico.yy"
{moveCol();return MOD;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "lexico.yy"
{moveCol();return EQUAL;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 "lexico.yy"
{moveCol();return QUESTION_MARK;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 76 "lexico.yy"
{moveCol();return OR_LOGIC;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 77 "lexico.yy"
{moveCol();return AND_LOGIC;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 78 "lexico.yy"
{moveCol();return INCREMENT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 "lexico.yy"
{moveCol();return DECREMENT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 "lexico.yy"
{moveCol();return NOT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "lexico.yy"
{moveCol();return NOT_BIT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "lexico.yy"
{moveCol();return OR;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "lexico.yy"
{moveCol();return OR_EXC;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "lexico.yy"
{moveCol();return AND;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "lexico.yy"
{moveCol();return IF;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "lexico.yy"
{moveCol();return ELSE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "lexico.yy"
{moveCol();return WHILE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "lexico.yy"
{moveCol();return NEW;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "lexico.yy"
{moveCol();return DO;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "lexico.yy"
{moveCol();return FOR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "lexico.yy"
{moveCol();return BREAK;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "lexico.yy"
{moveCol();return CONTINUE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "lexico.yy"
{moveCol();return GOTO;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "lexico.yy"
{moveCol();return RETURN;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 95 "lexico.yy"
{moveCol();return CASE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 96 "lexico.yy"
{moveCol();return SWITCH;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 97 "lexico.yy"
{moveCol();return DEFAULT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 98 "lexico.yy"
{moveCol();return TRANSIENT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 99 "lexico.yy"
{moveCol();return VOLATILE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 100 "lexico.yy"
{moveCol();return FINAL;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 101 "lexico.yy"
{moveCol();return CLASS;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 102 "lexico.yy"
{moveCol();return STATIC;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 103 "lexico.yy"
{moveCol();return VOID;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 104 "lexico.yy"
{moveCol();return PUBLIC;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 105 "lexico.yy"
{moveCol();return MAIN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 106 "lexico.yy"
{moveCol();return ARGS;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 107 "lexico.yy"
{moveCol();return TYPE_INT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 108 "lexico.yy"
{moveCol();return TYPE_SHORT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 109 "lexico.yy"
{moveCol();return TYPE_LONG;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 110 "lexico.yy"
{moveCol();return TYPE_BYTE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 111 "lexico.yy"
{moveCol();return TYPE_BOOL;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 112 "lexico.yy"
{moveCol();return TYPE_FLOAT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 113 "lexico.yy"
{moveCol();return TYPE_DOUBLE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 114 "lexico.yy"
{moveCol();return TYPE_CHAR;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 115 "lexico.yy"
{moveCol();return TYPE_STRING;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 116 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 117 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 118 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 119 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 120 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 121 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LOGIC_ASSIGN;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 122 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return SHIFT_ASSIGN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 123 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return ARITH_ASSIGN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 124 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return EQUALOP;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 125 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return RELOP;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 126 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return SHIFTS;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 127 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 128 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 129 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 130 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 131 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return LITERAL;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 132 "lexico.yy"
{moveCol();yylval.strval = strdup(yytext);return ID;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 136 "lexico.yy"
ECHO;
	YY_BREAK
#line 1466 "lexico.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 251 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 251 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 250);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 136 "lexico.yy"




int yywrap(){
   return 1;
}


void moveLine(){
   /**segue para proxima linha e reinicia a coluna**/
   line++;
   column = 1;
}

void moveCol(){
   /**segue para proxima coluna**/
   column += yyleng;
}


